FROM golang:1.14-alpine

RUN apk add --update --no-cache ca-certificates cmake make g++ openssl-dev git curl pkgconfig

WORKDIR $GOPATH/src/github.com/opensentry/idp

COPY . .

# Fix warning:
#go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
#	ignoring go.mod;
#	see 'go help modules'
# RUN rm go.mod go.sum

RUN go get -d -v ./...

RUN go get github.com/ivpusic/rerun

EXPOSE 443

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["rerun", "-a--serve"]
